export const en: Record<string, string> = {
  "?": "Kick",
  "? ?": "Three notes",
  "? ?, ? ?, ? ?": "One note, two notes, three notes",
  "? ?? ??? ????": "Listen to two chords",
  "? ????!": "Well done!",
  "? ?????!": "Listen carefully!",
  "? (Am)": "La (Am)",
  "? (Bdim)": "Ti (Bdim)",
  "? (C)": "Do (C)",
  "? (Dm)": "Re (Dm)",
  "? (Em)": "Mi (Em)",
  "? (F)": "Fa (F)",
  "? (G)": "Sol (G)",
  "? + ?": "Do + Re",
  "?:": "Notes:",
  "??": "OK",
  "?? ? ?? ?????!": "Sing a little higher!",
  "?? ? ???!": "Almost there!",
  "?? ? ?????": "Add more notes",
  "?? ??": "Bright feeling",
  "?? ?? ??": "Explore sound waves",
  "?? ?? ?? ?? ??????!": "Tap cells to place notes, then play them!",
  "?? ?? ???? ??????!": "Tap cells to create a melody!",
  "?? ?? ????!": "Wonderful ears!",
  "?? ?? ?...": "Loading instrument...",
  "?? ??:": "Current speed:",
  "?? ??!": "Good choice!",
  "?? ???": "Reference Guide",
  "?? ???:": "Rhythm Maker:",
  "?? ????": "Recommended Activities",
  "?? ?????": "Use fewer notes",
  "?? ?...": "Listening...",
  "?? ${noteCount < 3 ? '? ?????' : '?????'}": "Adjust the number of notes",
  "???": "Bright",
  "??? ??": "Learning Mode",
  "??? ?? ??": "Explore instrument sounds",
  "??? ?? ??? ?? ??? ??? ?????.": "Draw notes on the piano roll to complete your melody.",
  "??? ?? ??? ????": "Turn on sound and tap the screen",
  "??? ?? ??? ?????.": "Microphone permission is required.",
  "??? ?? ??? ????.": "Microphone access is required.",
  "??? ?? ?????!": "Sing the note you remember!",
  "??? ???": "Sound Waves",
  "??? ??? ??": "Connecting Sight and Sound",
  "??? ??? ??? ???? ??? ???.": "Explore and create music in a playful way.",
  "??? ??? ???? ??": "Comfortable and tense sounds",
  "??? ??? ???? ??????": "Tap the screen to enable audio",
  "??? ???:": "Melody Maker:",
  "??? ????": "Transform your voice",
  "??? ???? 4?? ??? ?????.": "Choose four chords that fit your beat.",
  "??? ?????": "Listen to the pattern",
  "??? ?????!": "Keep it there!",
  "??? ??????": "How do I use it?",
  "??? ????...": "Wait just a moment...",
  "??? ?...": "Recording...",
  "???!": "Great!",
  "???! ??": "Great! ??",
  "????": "Dark",
  "???? ?? ??": "Compose melodies and chords",
  "???? ?? ?? ?? ???? ?????.": "All the track parts you made have been combined.",
  "???? ?? ??? ?????!": "Turn on the microphone and sing!",
  "???? ?? ???? ??, Zam": "A playful world of music, Zam",
  "???? ?? ?????": "Tap the microphone to record",
  "???? ??? ??? ????.": "Learn the basics of music step by step.",
  "???? ????": "Play with drawings",
  "???? ??????? ???? ????... (? 8? ??)": "Audio is recording in the background... (about 8 seconds)",
  "????:": "Kandinsky:",
  "????!": "Amazing!",
  "????! ?? ??????": "Not quite! Let?s listen again.",
  "????! ??? ?????.": "Perfect! Keep it there.",
  "?????": "Arpeggio",
  "????? ??": "Rhythmic chords",
  "????? ???? ?? ??": "Guide for neurodiversity caregivers",
  "??????? (???)": "Playground (Play Lab)",
  "\"쿵-쿵-쿵쿵쿵\". 2박 뒤부터 쪼개지는 3연타가 핵심.": "“Thump-thump-thump thump”. The key is three consecutive hits starting after two nights.",
  "\"쿵-쿵-팍-쿵\" 대중음악의 가장 표준적인 리듬.": "“Knock-knock-pak-kung” The most standard rhythm in popular music.",
  "${patternIdx + 1}?? ??? ??????!": "Follow sound ${patternIdx + 1}!",
  "${patternIdx + 1}번째 소리를 따라해보세요!": "${patternIdx + 1}번째 소리를 따라해보세요!",
  "1. ?? ???": "1. Make a Rhythm",
  "1. 리듬 만들기": "1. 리듬 만들기",
  "16?? ?? ???? ??? ??? ?????.": "Build an exciting beat with the 16-step drum machine.",
  "16비트 드럼 머신으로 신나는 비트를 찍어보세요.": "16비트 드럼 머신으로 신나는 비트를 찍어보세요.",
  "2. ?? ???": "2. Make Chords",
  "2. 화음 만들기": "2. 화음 만들기",
  "2박 뒷박(앤)을 강조해 펑키하고 쫄깃한 느낌을 줌.": "It gives a funky and chewy feel by emphasizing the second beat (ann).",
  "3. ??? ???": "3. Make a Melody",
  "3. 멜로디 만들기": "3. 멜로디 만들기",
  "4박 그리드 위에 음을 놓아보세요": "Place notes on the 4-beat grid",
  "8?? ??": "Basic 8-Beat",
  "8비트 기본": "8-bit basic",
  "가볍게 즐기며 음악을 탐구하고 만들어 보세요.": "Have fun exploring and creating music.",
  "가장 높은 소리까지 정확하게 맞춰보세요.": "Accurately tune even the highest sounds.",
  "가장 흔하게 쓰이는 8가지 리듬 패턴을 직접 들어보세요.": "Listen to the eight most commonly used rhythm patterns.",
  "같은 음 찾기": "Find the same note",
  "같은 음 찾기 (기초)": "Finding the same note (basics)",
  "같은 음인데 느낌이 달라요!": "It's the same note, but it feels different!",
  "거꾸로": "upside down",
  "거의 다 왔어요!": "We're almost there!",
  "경쾌한 락/펑크. 빠른 속도로 연주되는 베이직 비트.": "Upbeat rock/punk. Basic beat played at fast speed.",
  "계단을 올라가요 \"도-레-미\"": "Go up the stairs \"Do-re-mi\"",
  "곧 재미있는 레슨이 추가될 예정이에요.": "More fun lessons will be added soon.",
  "구름이 낀 느낌이에요": "It feels like there are clouds",
  "귀를 기울여 똑같은 높이를 찾아요": "Listen and find the same height",
  "규칙적인 패턴이나 반복적인 행동을 좋아하는 아이들에게 안정감을 줍니다.": "It provides a sense of stability to children who like regular patterns or repetitive actions.",
  "그대로 유지하세요!": "Keep it that way!",
  "그림 그리기와 소리가 결합되어 있어, 자신만의 그림이 어떤 소리가 나는지 호기심을 자극하기 좋습니다.": "Because drawing and sound are combined, it's great for stimulating curiosity about what sounds your own drawings sound like.",
  "그림으로 연주하기": "Playing with Pictures",
  "기본 비트": "basic bits",
  "기본 소리 위에 쌓아볼까요?": "Shall we build on the basic sounds?",
  "기억한 음을 불러보세요!": "Sing the notes you memorized!",
  "긴장": "nervous",
  "긴장돼요": "I'm nervous",
  "깊어요": "깊어요",
  "깜빡이는 빛과 소리에 맞춰 고개를 끄덕여보세요": "Nod your head to the blinking lights and sounds",
  "나만의 리듬 만들기": "Create your own rhythm",
  "나만의 멋진 리듬을 완성해요": "Complete your own wonderful rhythm",
  "나의 목소리": "my voice",
  "낮": "afternoon",
  "낮 → 중 → 높": "Low → Medium → High",
  "낮은 소리": "low sound",
  "낮은 소리(코끼리)는 어디있나요?": "Where is the low sound (elephant)?",
  "낮은 음 따라 부르기": "sing along low notes",
  "낮음 → 높음": "Low → High",
  "내려가기": "go down",
  "네번째 이야기": "fourth story",
  "높": "high",
  "높 → 중 → 낮": "High → Medium → Low",
  "높은 소리": "high sound",
  "높은 소리 도전!": "High sound challenge!",
  "높은 소리(새)는 어디있나요?": "Where is the high sound (bird)?",
  "높은 소리와 낮은 소리": "high and low sounds",
  "높음 → 낮음": "High → Low",
  "눌러서 들어보세요": "Click to listen",
  "눌러서 소리를 들어보세요": "Click to hear the sound",
  "다른 소리도 올려봐요!": "Try uploading other sounds too!",
  "다시 경쾌하게!": "Cheerful again!",
  "다시 들어보고 마음에 드는 소리를 골라보세요": "Listen again and choose the sound you like",
  "다시 한번 도전!": "Challenge again!",
  "다양한 리듬 체험": "Various rhythm experiences",
  "다양한 리듬 패턴을 만들어요": "Create various rhythm patterns",
  "다양한 악기 소리": "various instrument sounds",
  "다양한 악기와 소리를 자유롭게 만지며 실험하는 공간입니다. 정답이 없으므로 아이가 좋아하는 소리나 시각적 반응을 보이는 도구를 자유롭게 탐색하도록 격려해 주세요.": "This is a space where you can freely experiment with various instruments and sounds. There is no one right answer, so encourage your child to explore tools that provide sounds or visual responses that they like.",
  "다음": "다음",
  "단계별로 음악의 기초를 익힐 수 있습니다. 아이의 속도에 맞춰 천천히 진행하며, 한 단계를 완료할 때마다 긍정적인 피드백을 주시는 것이 좋습니다.": "You can learn the basics of music step by step. It's a good idea to progress slowly, at your child's pace, and provide positive feedback as each step is completed.",
  "단순하고 경쾌함. 펑크 락이나 트로트의 기초.": "Simple and cheerful. The basis of punk rock or trot.",
  "닫기": "닫기",
  "대단해요!": "It's amazing!",
  "도": "do",
  "도 (C)": "도 (C)",
  "도 + 레": "do + re",
  "도 + 미": "do + me",
  "독특한 킥 바운스와 잘게 쪼개지는 하이햇.": "Unique kick bounce and shredding hi-hat.",
  "동시에 나는 소리": "sounds made at the same time",
  "두 가지 조합을 다시 들어보세요": "Listen to both combinations again",
  "두 가지 화음을 들어볰요": "I heard two chords.",
  "두 번째 도전!": "Second challenge!",
  "두 번째 소리가 어땠나요?": "What did the second sound like?",
  "두 소리가 함께 울리는 경험": "The experience of two sounds sounding together",
  "두 소리를 겹쳐볼까?": "Should we overlap the two sounds?",
  "두 음": "two notes",
  "두 음을 직접 쌓아보기": "Stack the two notes yourself",
  "두 음의 움직임을 따라 불러보세요.": "Sing along with the movements of the two notes.",
  "두번째 이야기": "second story",
  "뒤로가기": "Go back",
  "뒷박을 강조해 펑키하고 쫄깃한 느낌.": "The emphasis on the back beat gives it a funky and chewy feel.",
  "드럼 머신 스튜디오": "drum machine studio",
  "드럼 비트 제작": "drum beat production",
  "듣는 중...": "Listening...",
  "들어보기": "listen",
  "땅": "earth",
  "똑같은 음인데 한 음만 달라요!": "It's the same note, but only one note is different!",
  "라": "la",
  "라 (Am)": "라 (Am)",
  "라틴 리듬의 정수. 세련된 당김음으로 부드러운 분위기.": "The essence of Latin rhythm. A soft atmosphere with sophisticated syncopation.",
  "라틴 보사노바 크라베 패턴과 부드러운 리듬.": "Latin bossanova crave pattern and smooth rhythm.",
  "레": "Re",
  "레 (Dm)": "레 (Dm)",
  "레슨": "레슨",
  "레슨 준비 중...": "Preparing for lesson...",
  "리드미컬한 화음": "rhythmic chords",
  "리듬": "rhythm",
  "리듬 마스터": "rhythm master",
  "리듬 메이커": "rhythm maker",
  "리듬 메이커:": "Rhythm Maker:",
  "리듬 위에 음 놓기": "Put notes on rhythm",
  "리듬 위에 음을 놓아봐요": "Let's put the note on top of the rhythm",
  "리듬 위의 멜로디": "melody over rhythm",
  "리듬 패턴": "rhythm pattern",
  "리듬의 기초": "Rhythm Basics",
  "마이크 사용 권한이 필요합니다.": "Microphone permission is required.",
  "마이크 접근 권한이 필요해요.": "Microphone access is required.",
  "마이크로 직접 소리를 내보세요": "Make sounds directly with the microphone",
  "마이크를 눌러 녹음하세요": "Tap the microphone to record",
  "마이크를 켜고 노래를 불러보세요!": "Turn on the mic and sing!",
  "마지막 단계": "final step",
  "마지막 도전!": "Last challenge!",
  "마지막! 이 소리는?": "last! What is this sound?",
  "마지막! 이 화음은?": "last! What is this chord?",
  "마지막으로 차분하게": "Finally, calmly",
  "먼저 소리를 듣고, 느낌을 골라보세요": "Listen to the sound first, then choose a feeling",
  "먼저 아래 소리를 들어보세요": "First listen to the sound below",
  "먼저 하나의 소리를 들어보세요": "Listen to one sound first",
  "멈춤": "stoppage",
  "멋진 귀를 가졌어요!": "You have great ears!",
  "멋진 멜로디! 재생하거나 완료하세요": "Great melody! Play or Complete",
  "멜로디": "melody",
  "멜로디 메이커": "melody maker",
  "멜로디 메이커:": "Melody Maker:",
  "멜로디와 화음 작곡": "Composing melodies and chords",
  "모든 활동은 소리와 함께 직관적인 시각적 피드백을 제공합니다. 이는 감각 통합을 돕고 직관적인 이해를 높여줍니다.": "All activities provide intuitive visual feedback with sound. This aids sensory integration and increases intuitive understanding.",
  "목소리 변형하기": "Transform your voice",
  "목소리로 맞춰보기": "Guess by voice",
  "목표 음높이": "target pitch",
  "무작위": "random",
  "미": "mi",
  "미 (Em)": "미 (Em)",
  "바이올린": "violin",
  "박자란 무엇일까?": "What is beat?",
  "박자를 느껴봐요": "Feel the beat",
  "반대로 내려오는 움직임이에요.": "On the contrary, it is a downward movement.",
  "반복 있음": "There is repetition",
  "반복 패턴을 만들어보세요 (같은 위치에 놓기)": "Create repeating patterns (place them in the same place)",
  "반복 필요": "need repeat",
  "밝아요": "It's bright",
  "밝은 느낌": "bright feeling",
  "밝은 느낌 (장조)": "Bright feeling (major)",
  "밝은 화음, 어두운 화음": "bright chords, dark chords",
  "밝음": "bright",
  "방금 전보다 심장이 빨리 뛰는 것 같죠?": "Does it feel like your heart is beating faster than before?",
  "배경 음악": "background music",
  "배우기": "learning",
  "배우기 모드": "learn mode",
  "배음 (Harmonics)": "Harmonics",
  "배음 원리 탐구": "Exploring the overtone principle",
  "베이스의 낮은 소리를 따라 해보세요. (아— 하고 소리내면 분석이 쉬워져요)": "Try imitating the low sound of the bass. (Ah, if you say it out loud it becomes easier to analyze)",
  "보사노바": "bossa nova",
  "보이스 스피너": "voice spinner",
  "블록마다 다른 소리가 나요": "Each block makes a different sound",
  "블록으로 봐요": "Look at it in blocks",
  "블록을 드래그해서 순서를 바꿔보세요": "Drag blocks to change their order",
  "블록을 배열해서 멜로디 선을 그려보세요": "Arrange blocks to draw a melody line",
  "블록을 쌓듯 색깔 네모를 클릭하여 멜로디를 만드는 직관적인 활동입니다.": "This is an intuitive activity that creates a melody by clicking on colored squares as if stacking blocks.",
  "비트와 어울리는 4개의 화음을 골라주세요.": "비트와 어울리는 4개의 화음을 골라주세요.",
  "빈 그리드 위에 직접 창의적인 리듬을 만들어보세요!": "Create creative rhythms directly on the blank grid!",
  "빠르게": "fast",
  "빨간색 버튼을 눌러보세요": "Press the red button",
  "사운드 웨이브": "sound wave",
  "산 모양": "mountain shape",
  "새소리와 코끼리 소리를 비교해봐요": "Compare the sounds of birds and elephants.",
  "세 개의 음으로 선을 그려봐요": "Draw a line with three notes",
  "세 소리가 만드는 풍성함": "The richness created by three sounds",
  "세 소리를 함께 들어보세요": "Listen to the three sounds together",
  "세 음": "three notes",
  "세 음 패턴": "three note pattern",
  "세 음 패턴 만들기": "Create a three note pattern",
  "세 음 화음": "three note chord",
  "세번째 이야기": "third story",
  "셋잇단음표 기반. 블루스나 바운스 있는 댄스곡.": "Based on triplet notes. A dance song with blues or bounce.",
  "셋잇단음표 느낌의 바운스. 블루스와 재즈 기반.": "A triplet-like bounce. Based on blues and jazz.",
  "셔플/스윙": "Shuffle/Swing",
  "소리 그리기": "drawing sound",
  "소리 놀이터": "sound playground",
  "소리 쌓기": "building up sound",
  "소리 파동 체험": "sound wave experience",
  "소리가 내려가요": "The sound goes down",
  "소리가 아래로 움직이는 걸 느껴보세요": "Feel the sound moving down",
  "소리가 올라가요": "The sound goes up",
  "소리가 위로 움직이는 걸 느껴보세요": "Feel the sound moving upward",
  "소리가 위아래로 움직이는 것을 느껴봐요": "Feel the sound moving up and down",
  "소리는 위아래로 움직여요": "The sound moves up and down",
  "소리를 듣고 방향을 골라보세요": "Listen to the sound and choose your direction",
  "소리를 듣고 잠시 뒤에 불러보세요": "Listen to the sound and call it later.",
  "소리를 블록으로 보기": "View sounds as blocks",
  "소리를 블록으로 봐요": "Look at sounds as blocks",
  "소리를 잘 듣고, 사라진 뒤에 똑같이 불러보세요.": "Listen carefully to the sound, and then sing the same song after it disappears.",
  "소리를 켜고 화면을 탭하세요": "Turn on sound and tap the screen",
  "소리를 하나씩 더해볼까요?": "Shall we add sounds one by one?",
  "소리의 겹침": "overlap of sounds",
  "소리의 높고 낮음은 위아래 움직임과 같아요.": "The high and low pitch of a sound is the same as the up and down movement.",
  "소리의 높낮이 탐험": "Exploring the pitch and pitch of sound",
  "소리의 방향": "direction of sound",
  "속도가 무작위로 바뀝니다. 잘 듣고 따라오세요": "The speed changes randomly. Listen carefully and follow along.",
  "손가락으로 그림을 그려보세요!": "Paint with your fingers!",
  "솔": "brush",
  "솔 (G)": "솔 (G)",
  "솔까지 올라가볼까요?": "Shall we go up to Sol?",
  "순서를 바꿔볼까요?": "Shall we change the order?",
  "스네어": "snare",
  "슬라이더를 위아래로 움직여서 소리의 움직임을 느껴보세요.": "Move the slider up or down to feel the sound in motion.",
  "슬퍼요": "슬퍼요",
  "슬픈 느낌": "feeling sad",
  "슬픈 느낌 (단조)": "feeling sad (minor)",
  "시 (Bdim)": "시 (Bdim)",
  "시각과 청각의 연결": "The connection between sight and hearing",
  "시간 순서": "chronological order",
  "시공 중!": "Under construction!",
  "시작하기!": "Get started!",
  "신나요": "신나요",
  "실험실": "laboratory",
  "씩씩해요": "씩씩해요",
  "아래 줄을 하나씩 눌러보세요. 그리고 함께 눌러보세요!": "Please click on the lines below one by one. And press together!",
  "아래로": "down",
  "아르페지오": "arpeggio",
  "악기 로딩 중...": "Loading instrument...",
  "악기 탐험": "exploring musical instruments",
  "안정적": "stable",
  "알 수 없는 유닛": "unknown unit",
  "어느 게 가장 풍성하게 들렸나요?": "Which one sounded richest?",
  "어느 쪽으로 움직였나요?": "Which way did you move?",
  "어느 쪽이 \"밝은\" 느낌인가요?": "Which one feels “bright”?",
  "어두움": "gloominess",
  "어두워요": "It's dark",
  "어떤 소리가 더 높을까요?": "Which sound is higher?",
  "어떤 소리가 마음에 드나요?": "What sound do you like?",
  "어떤 소리를 올려볼까요?": "What kind of sound should we raise?",
  "어떤 순서가 좋았나요?": "What order did you like?",
  "어떤 조합이 더 안정적이었나요?": "Which combination was more stable?",
  "어떻게 사용하나요?": "How do I use it?",
  "어울림과 긴장": "harmony and tension",
  "엇박 강조": "mismatched emphasis",
  "엇박과 정박을 섞어 묵직하고 트렌디한 무게감 형성.": "Create a heavy and trendy sense of weight by mixing offset and anchored beats.",
  "여기에 쌓아보세요": "Build it here",
  "여러 소리 조합을 들어보세요": "Listen to different sound combinations",
  "오디오가 백그라운드에서 녹음되고 있습니다... (약 8초 소요)": "오디오가 백그라운드에서 녹음되고 있습니다... (약 8초 소요)",
  "올라가기": "go up",
  "완벽해요! 그대로 유지하세요.": "Perfect! Keep it that way.",
  "왔다갔다": "back and forth",
  "왼쪽 스피커 버튼을 눌러 소리를 듣고, 똑같은 높이를 찾아보세요.": "Press the left speaker button to hear the sound and find the same height.",
  "위로": "consolation",
  "위로 쌓이면 동시에, 옆으로 이어지면 차례대로!": "If stacked upwards, at the same time, if stacked sideways, one after the other!",
  "위아래로 스와이프하여 파동을 연주해보세요": "Swipe up and down to play waves",
  "위에 올릴 소리를 골라보세요": "Choose a sound to put on top",
  "유닛 1": "unit 1",
  "유닛 2": "unit 2",
  "유닛 3": "unit 3",
  "유닛 4": "unit 4",
  "음 기억하기": "Well remember",
  "음 높이 퀴즈": "pitch quiz",
  "음 패턴 따라하기": "Follow the note pattern",
  "음높이": "pitch",
  "음높이 마스터!": "Pitch Master!",
  "음높이란 무엇일까?": "What is pitch?",
  "음높이의 기초": "basics of pitch",
  "음악으로 노는 재미있는 세상, Zam": "음악으로 노는 재미있는 세상, Zam",
  "음악의 규칙적인 박동을 느껴봐요": "Feel the rhythmic beat of the music",
  "음악이 앞으로 나아가게 하는 일정한 맥박이에요": "It's a steady pulse that moves the music forward.",
  "음을 ${noteCount < 3 ? '더 놓아주세요' : '줄여주세요'}": "음을 ${noteCount < 3 ? '더 놓아주세요' : '줄여주세요'}",
  "이 소리 위에 다른 소리를 쌓아볼 거예요": "I'm going to build another sound on top of this sound.",
  "이 소리는 어떤 느낌이에요?": "What does this sound feel like?",
  "이 소리는 어떤가요?": "What does this sound like?",
  "이 소리도 들어볼까요?": "Shall we listen to this too?",
  "이번에는 음높이의 차이가 조금 더 작아졌어요.": "This time the pitch difference is a little smaller.",
  "이번에도 소리를 잘 기억해야 해요.": "This time too, you have to remember the sound well.",
  "이번엔 다른 소리를 골라보세요": "Choose a different sound this time",
  "이번엔 두 개의 소리가 동시에 나요!": "This time, two sounds sound at the same time!",
  "이번엔 좀 더 높은 소리에 도전해볼까요?": "Shall we try a higher sound this time?",
  "이번엔 좀 더 느리게~": "A little slower this time~",
  "이번엔 좀 더 빠르게!": "A little faster this time!",
  "이번엔?": "This time?",
  "이제 박자의 고수! 완벽하게 맞춰볼까요?": "Now you're a master of beats! Shall we match it perfectly?",
  "잘 들어보세요!": "Listen carefully!",
  "잘게 쪼개지는 16비트 하이햇과 묵직한 808 킥.": "Crunchy 16-bit hi-hats and heavy 808 kick.",
  "잠시만 기다려요...": "Just wait...",
  "저지 클럽": "jersey club",
  "정박": "정박",
  "정해진 코드진행 위에서 멜로디를 만들어보세요": "Create a melody based on a set chord progression",
  "조금 더 낮게 불러보세요!": "조금 더 낮게 불러보세요!",
  "조금 더 높게 불러보세요!": "조금 더 높게 불러보세요!",
  "조금 더 높은 소리까지 정확하게 맞춰볼까요?": "Shall we try to accurately match a slightly higher sound?",
  "조금 더 높은 음": "a little higher pitch",
  "조깅을 하는 속도예요": "It's jogging speed.",
  "조합 A": "Combination A",
  "조합 B": "Combination B",
  "조합 C": "Combination C",
  "조합 D": "Combination D",
  "종소리": "knell",
  "좋아요!": "great!",
  "좋아요! 👂": "great! 👂",
  "좋은 귀를 가졌어요!": "You have great ears!",
  "좋은 선택!": "Good choice!",
  "줄을 튕겨보세요": "Pluck the string",
  "중": "middle",
  "중 → 높 → 중": "Middle → High → Middle",
  "중간 음 높이": "medium pitch",
  "즐거운 화음 실험": "fun chord experiment",
  "지금까지 만든 모든 트랙 요소들이 합쳐졌어요.": "지금까지 만든 모든 트랙 요소들이 합쳐졌어요.",
  "직접 겹쳐봐요!": "Try overlapping them yourself!",
  "집중해서 들어보세요. 어느 쪽일까요?": "Listen carefully. Which one?",
  "짧은 멜로디의 움직임을 따라가요": "Follow the movements of the short melody",
  "차근차근 음악의 기초를 배워봐요.": "Let’s learn the basics of music step by step.",
  "차례대로 나는 소리": "sounds made in sequence",
  "차분해요": "차분해요",
  "참 잘했어요!": "Well done!",
  "처음으로": "처음으로",
  "천천히": "slowly",
  "천천히 여유롭게 걸어가는 느낌이에요": "I feel like I'm walking slowly and leisurely.",
  "첫 번째 도전!": "First challenge!",
  "첫 번째 소리를 듣고, 두 번째 소리가 더 높은지 낮은지 맞춰보세요.": "Listen to the first sound and guess whether the second sound is higher or lower.",
  "첫 번째 음 \"도\"": "The first note “do”",
  "첫번째 이야기": "first story",
  "친구들을 모두 눌러서 멋진 합창을 만들어보세요!": "Tap on all your friends to create a great chorus!",
  "카운트다운 후 나오는 소리에 맞춰 버튼을 눌러보세요": "Press the button according to the sound that appears after the countdown.",
  "칸딘스키": "kandinsky",
  "칸딘스키:": "Kandinsky:",
  "칸을 눌러 멜로디를 만들어보세요!": "칸을 눌러 멜로디를 만들어보세요!",
  "칸을 눌러 음을 놓고 재생해보세요!": "Click on the box to set the note and play it!",
  "코드 메이커": "code maker",
  "코드 위에서 멜로디를 만들어봐요": "Create a melody on chords",
  "코드 위의 멜로디": "melody on chords",
  "쿵!": "thud!",
  "쿵짝쿵짝 기본 비트를 익혀요": "Learn the basic beats",
  "킥": "kick",
  "킥, 스네어, 하이햇이 조합된 16스텝 시퀀서로 리듬을 파악해보세요.": "Figure out the rhythm with a 16-step sequencer that combines kick, snare, and hi-hat.",
  "투 비트": "two beat",
  "트랙 완성!": "트랙 완성!",
  "트랩/힙합": "Trap/Hip Hop",
  "트럼펫": "trumpet",
  "틀렸어요! 다시 들어볼까요?": "틀렸어요! 다시 들어볼까요?",
  "파": "green onion",
  "파 (F)": "파 (F)",
  "팝/락의 정석. \"쿵 쿵 팍 쿵\" 하는 안정적인 추진력.": "The essence of pop/rock. A steady momentum of “thump thump thump thump”.",
  "패턴을 들어보세요": "listen for the pattern",
  "편안하게 숨을 쉬는 속도예요": "This is the speed at which you can breathe comfortably.",
  "편안한 느낌인지, 긴장되는 느낌인지 느껴보세요": "Notice whether you feel relaxed or tense.",
  "편안한 목소리로 따라 불러보세요.": "Sing along in a comfortable voice.",
  "편안한 소리와 긴장되는 소리": "Relaxing sounds and relaxing sounds",
  "편안해요": "It's comfortable",
  "풍성한 소리를 느껴보세요": "Experience rich sound",
  "플레이그라운드 (실험실)": "Playground (Laboratory)",
  "피아노": "piano",
  "피아노 롤에 노트를 그려 나만의 선율을 완성하세요.": "피아노 롤에 노트를 그려 나만의 선율을 완성하세요.",
  "하늘": "sky",
  "하모닉스": "Harmonics",
  "하이햇": "하이햇",
  "하프 소리 연주": "playing harp sound",
  "하프 스트링": "half strings",
  "한 음": "one note",
  "한 음, 두 음, 세 음": "One note, two notes, three notes",
  "한 음을 들어봐요": "Listen to one note",
  "한 친구의 목소리를 들어보세요.": "Listen to the voice of a friend.",
  "함께 들어보기": "Listen together",
  "해가 쨍쨍한 느낌이에요": "It feels like the sun is shining brightly",
  "행복해요": "행복해요",
  "현재 속도:": "Current speed:",
  "혼자 부르는 노래 (솔로)": "A song sung alone (solo)",
  "화면을 탭하여 오디오를 활성화하세요": "Tap the screen to activate audio",
  "화음": "Chinese pronunciation",
  "화음 만들기": "Create chords",
  "화음 블록": "chord blocks",
  "화음 연주": "playing chords",
  "화음 조합 학습": "Learning chord combinations",
  "화음은 흘러가요": "The chord flows",
  "화음을 골라주세요": "Please choose a chord",
  "화음의 움직임": "chord movement",
  "화음이 가진 감정 느끼기": "Feel the emotions of chords",
  "화음이 뭘까?": "What is a chord?",
  "화음이 어떻게 움직이는지 블록으로 확인해보세요": "Check out the blocks to see how the chords move",
  "화음이 움직여요": "The chords move",
  "화음이 차례대로 바뀌는 걸 들어보세요": "Listen to the chords change one after another.",
  "EDM, 하우스의 표준. 모든 박자에 킥이 들어감.": "EDM, the standard of house. A kick is added to every beat.",
  "EDM의 핵심. 킥 4번, 엇박 하이햇과 정박 스네어.": "The core of EDM. Kick number 4, off-beat hi-hat and anchored snare.",
  "ZAM ?? ???": "ZAM User Guide",
  "Zam (?)": "Zam",
  "Zam (잼)": "Zam (잼)",
  "ZAM 이용 가이드": "ZAM User Guide",
  "zam-(?)": "zam",
  "zam-(잼)": "zam-(잼)"
};
